spring.application.name=creen_carry_back

# server port
server.port=10400

#oracle settings
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@1.223.77.178:15211/XEPDB1
spring.datasource.username=TEAM2_DB
spring.datasource.password=2222

#mybatis settings
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**.xml
mybatis.type-aliases-package=kr.co.iei



# google mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shinjiwoong1656@gmail.com
spring.mail.password=wrfqoqbxdddytsmk
spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

