spring.application.name=green_carry_back

# server port
server.port=${PORT:10400}

# shared folder root
#file.upload.path=\\\\192.168.31.26\\project

# file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# database
spring.datasource.driver-class-name=${DB_DRIVER:oracle.jdbc.OracleDriver}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#mybatis settings
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**.xml
mybatis.type-aliases-package=kr.co.iei
mybatis.configuration.jdbc-type-for-null=NULL

# Toss
TOSS_SECRET_KEY=${TOSS_SECRET_KEY}

# Naver Map
naver.geocode.client.id=${NAVER_GEOCODE_CLIENT_ID}
naver.geocode.client.secret=${NAVER_GEOCODE_CLIENT_SECRET}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Brevo
brevo.api-key=${BREVO_API_KEY}
brevo.sender-email=${BREVO_SENDER_EMAIL}
brevo.sender-name=${BREVO_SENDER_NAME:GreenCarry}

#spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
#spring.data.redis.port=${SPRING_DATA_REDIS_PORT:11233}
#spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}

#spring.data.redis.lettuce.pool.max-active=10
#spring.data.redis.lettuce.pool.max-idle=10
#spring.data.redis.lettuce.pool.min-idle=2

#spring.data.redis.timeout=2000ms
