spring.application.name=green_carry_back

# server port
server.port=10400

# shared folder root
#file.upload.path=\\\\192.168.31.26\\project

# file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

#oracle settings
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@1.223.77.178:15211/XEPDB1
spring.datasource.username=TEAM2_DB
spring.datasource.password=2222



#mybatis settings
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**.xml
mybatis.type-aliases-package=kr.co.iei
mybatis.configuration.jdbc-type-for-null=NULL

# google mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shinjiwoong1656@gmail.com
spring.mail.password=wrfqoqbxdddytsmk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#toss secret key
TOSS_SECRET_KEY=test_sk_yZqmkKeP8g4KzaElDEwx3bQRxB9l

#naver map key
naver.geocode.client.id=1b7krfk6xp
naver.geocode.client.secret=X19xGdpptq7ewn5XzuX6pKxNYHy4GsQsXoPvoWFk

# application.properties
cloudinary.cloud-name=dgg37xl5m
cloudinary.api-key=185643916866631
# Root key Secret value
cloudinary.api-secret=Nyh67hOnFMiVxjAQSluUurH8H_s

#spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
#spring.data.redis.port=${SPRING_DATA_REDIS_PORT:11233}
#spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}

#spring.data.redis.lettuce.pool.max-active=10
#spring.data.redis.lettuce.pool.max-idle=10
#spring.data.redis.lettuce.pool.min-idle=2

#spring.data.redis.timeout=2000ms
